name: GH Pages Deploy

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache mdbook dependencies
        uses: actions/cache@v3
        id: mdbook-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-mdbook-${{ hashFiles('book.toml') }}

      - name: Install mdbook dependencies
        if: steps.mdbook-cache.outputs.cache-hit != 'true'
        run: |
          curl -sL https://github.com/cargo-bins/cargo-binstall/releases/download/v0.22.0/cargo-binstall-x86_64-unknown-linux-gnu.full.tgz \
          | tar -xzvf - -C $HOME/.cargo/bin \
          && cargo binstall --no-confirm --locked --github-token ${{ secrets.GITHUB_TOKEN }} \
          mdbook \
          mdbook-admonish \
          mdbook-footnote \
          mdbook-cmdrun

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with mdbook
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
